# Generated by Django 5.1.4 on 2025-01-21 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='entry_scores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('content', models.TextField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Genre',
            new_name='info',
        ),
        migrations.RenameModel(
            old_name='Author',
            new_name='Universities',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
